<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Cipher by three letters',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['results'] = array(
        'title' => 'Here are your results',
        'page callback' => 'show_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['input_value'] = array(
        '#title' => 'Shift Number',
        '#type' => 'textfield',
        '#description' => t('Enter a value to shift by'),
        '#element_validate' => array('element_validate_integer_positive'),
    );
    $form['input_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => t('Enter a direction to shift through'),
        '#element_validate' => array('element_validate_direction'),
    );
    $form['input_phrase'] = array(
        '#title' => 'Shift Word',
        '#type' => 'textfield',
        '#description' => t('Enter a word to shift through'),
        '#element_validate' => array('element_validate_special_characters'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'EnCipher!!!'
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['input_value'];
    $shift_direction = $form_state['values']['input_direction'];
    $shift_word = $form_state['values']['input_phrase'];
    $word_array = str_split($shift_word);
    $word_array_into_int = array();
    if ($shift_direction == 'left') {
        foreach($word_array as $element) {
            $element = ord($element) - 97;
            if($element < 0 || $element > 26) {
                $element+= 97;
                array_push($word_array_into_int, chr($element));
            }
            elseif($element - $shift_value < 0) {
                $element -= $shift_value;
                $element += 26;
                $element += 97;
                array_push($word_array_into_int, chr($element));
            }
            elseif ($element >= 0 && $element <= 26)
            {
                $element -= $shift_value;
                $element += 97;
                array_push($word_array_into_int, chr($element));
            }
        }
    }

    elseif ($shift_direction == 'right') {
        foreach($word_array as $element) {
            $element = ord($element) - 97;
            if($element < 0 || $element > 26) {
                $element += 97;
                array_push($word_array_into_int, chr($element));
            }
            elseif($element  + $shift_value > 26) {
                $element += $shift_value;
                $element %= 26;
                $element += 97;
                array_push($word_array_into_int, chr($element));
            }
            elseif ($element >= 0 && $element <= 26) {
                $element += $shift_value;
                $element += 97;
                array_push($word_array_into_int, chr($element));
            }
        }
    }
    $shifted_word = implode('', $word_array_into_int);
    $_SESSION['shifted_word'] = $shifted_word;
    $form_state['redirect'] = 'results';
}

function show_results() {
    $output = $_SESSION['shifted_word'];
    return $output;
}

function element_validate_direction($element) {
    $flag = 0;
    if ($element['#value'] == 'left') {
        $flag = 1;
    }
    if ($element['#value'] == 'right') {
        $flag = 1;
    }
    if ($flag = 0) {
        form_error($element, t('Direction must be left or right'));
    }
}

function element_validate_special_characters($element) {
    $check_this = $element['#value'];
    $check_this_split = str_split($check_this);
    foreach ($check_this_split as $element) {
        if ((ctype_alpha($element) == 0) && (ctype_punct($element) == 0)) {
            form_error($element, t('Only special characters are letters and punctuation'));
        }
    }
}
