<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Cipher by three letters',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['results'] = array(
        'title' => 'Here are your results',
        'page callback' => 'show_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['input_value'] = array(
        '#title' => 'Shift Number',
        '#type' => 'textfield',
        '#description' => 'Enter a value to shift by',
    );
    $form['input_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Enter a direction to shift through',
    );
    $form['input_phrase'] = array(
        '#title' => 'Shift Word',
        '#type' => 'textfield',
        '#description' => 'Enter a word to shift through',
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'EnCipher!!!'
    );
    return $form;
}

function cipher_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['input_value'];
    $shift_direction = $form_state['values']['input_direction'];
    $shift_word = $form_state['values']['input_phrase'];
    $word_array = explode(' ', $shift_word);
    $word_array_into_int = array();

    foreach($word_array as $element) {
        $element = ord($element) % 24;
        array.push($word_array_into_int, $element);
    }
    $_SESSION['shifted_word'] = $word_array_into_int;
    $form_state['redirect'] = 'results';
}

function show_results() {
    return $output;
}
