<?php

function cipher_menu() {
    $items = array();
    $items['cipher'] = array(
        'title' => 'Cipher by three letters',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
    $items['results'] = array(
        'title' => 'Here are your results',
        'page callback' => 'show_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

function cipher_form() {
    $form['input_value'] = array(
        '#title' => 'Shift Number',
        '#type' => 'textfield',
        '#description' => 'Enter a value to shift by',
    );
    $form['input_direction'] = array(
        '#title' => 'Shift Direction',
        '#type' => 'textfield',
        '#description' => 'Enter a direction to shift through',
    );
    $form['input_phrase'] = array(
        '#title' => 'Shift Word',
        '#type' => 'textfield',
        '#description' => 'Enter a word to shift through',
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'EnCipher!!!'
    );
    return $form;
}
